FORMAT: 1A
HOST: http://api.topcoder.com/v2

# Reviewer Management API

We extend the tc-api to provide new endpoints to handle admin / copilot / reviewer related
tasks.

## Admins Collection [/admin/admins]

### List All admins [GET]
+ Request (application/json)

    + Headers

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZHwxMzI0NTYiLCJleHAiOjEzOTI4MTc4ODQsImF1ZCI6InRvcGNvZGVyIiwiaWF0IjoxMzkyNzU3ODg0fQ.7X2IKkiyyI1ExSM5GNpdhJ8fGGK5-oAjzccX6YL_BKY



+ Response 200 (application/json)

        {
             "allAdmins": [
                {
                  "id": 132456,
                  "name": "heffan",
                  "adminGroup": true,
                  "adminRole": true,
                  "managerResource": true
                }]
        }

+ Response 401 (application/json)

        {
            "name":"Unauthorized",
            "value":"401",
            "description":"Authentication credentials were missing or incorrect."
        }

+ Response 403 (application/json)

        {
            "name":"Forbidden",
            "value":"403",
            "description":"The request is understood, but it has been refused or access is not allowed."
        }

+ Response 500 (application/json)

        {
            "name":"Internal Server Error",
            "value":"500",
            "description":"Unknown server error. Please contact support."
        }

+ Response 503 (application/json)

        {
            "name":"Service Unavailable",
            "value":"503",
            "description":"Servers are up but overloaded. Try again later."
        }
        
### Create New Admin [POST]
+ Attributes
    + username: `dok_tester` (required, string) ... The username
    
+ Request (application/json)

    + Headers

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZHwxMzI0NTYiLCJleHAiOjEzOTI4MTc4ODQsImF1ZCI6InRvcGNvZGVyIiwiaWF0IjoxMzkyNzU3ODg0fQ.7X2IKkiyyI1ExSM5GNpdhJ8fGGK5-oAjzccX6YL_BKY

   

+ Response 200 (application/json)
        
        {
             "success": true,
             "message": "dok_tester has been successfully added as TopCoder Admin"
        }
        
+ Response 400 (application/json)

        {
            "name":"Bad Request",
            "value":"400",
            "description":"The request was invalid. An accompanying message will explain why."
        }
        
+ Response 401 (application/json)

        {
            "name":"Unauthorized",
            "value":"401",
            "description":"Authentication credentials were missing or incorrect."
        }

+ Response 403 (application/json)

        {
            "name":"Forbidden",
            "value":"403",
            "description":"The request is understood, but it has been refused or access is not allowed."
        }

+ Response 404 (application/json)

        {
            "name":"Not Found",
            "value":"404",
            "description":"The URI requested is invalid or the requested resource does not exist."
        }

+ Response 409 (application/json)

        {
            "name":"Duplicate Resource",
            "value":"409",
            "description":"The request is understood, but has duplicate resource."
        }
        
+ Response 500 (application/json)

        {
            "name":"Internal Server Error",
            "value":"500",
            "description":"Unknown server error. Please contact support."
        }

+ Response 503 (application/json)

        {
            "name":"Service Unavailable",
            "value":"503",
            "description":"Servers are up but overloaded. Try again later."
        }
        
### Remove Admin [DELETE]
+ Attributes
    + username: `dok_tester` (required, string) ... The username
    
+ Request (application/json)

    + Headers

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZHwxMzI0NTYiLCJleHAiOjEzOTI4MTc4ODQsImF1ZCI6InRvcGNvZGVyIiwiaWF0IjoxMzkyNzU3ODg0fQ.7X2IKkiyyI1ExSM5GNpdhJ8fGGK5-oAjzccX6YL_BKY

   

+ Response 200 (application/json)
        
        {
             "success": true,
             "message": "TopCoder Admin: dok_tester has been successfully removed"
        }
        
+ Response 400 (application/json)

        {
            "name":"Bad Request",
            "value":"400",
            "description":"The request was invalid. An accompanying message will explain why."
        }
        
+ Response 401 (application/json)

        {
            "name":"Unauthorized",
            "value":"401",
            "description":"Authentication credentials were missing or incorrect."
        }

+ Response 403 (application/json)

        {
            "name":"Forbidden",
            "value":"403",
            "description":"The request is understood, but it has been refused or access is not allowed."
        }

+ Response 404 (application/json)

        {
            "name":"Not Found",
            "value":"404",
            "description":"The URI requested is invalid or the requested resource does not exist."
        }
        
+ Response 500 (application/json)

        {
            "name":"Internal Server Error",
            "value":"500",
            "description":"Unknown server error. Please contact support."
        }

+ Response 503 (application/json)

        {
            "name":"Service Unavailable",
            "value":"503",
            "description":"Servers are up but overloaded. Try again later."
        }

## Copilots Collection [/admin/copilots]

### List All copilots [GET]
+ Request (application/json)

    + Headers

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZHwxMzI0NTYiLCJleHAiOjEzOTI4MTc4ODQsImF1ZCI6InRvcGNvZGVyIiwiaWF0IjoxMzkyNzU3ODg0fQ.7X2IKkiyyI1ExSM5GNpdhJ8fGGK5-oAjzccX6YL_BKY



+ Response 200 (application/json)

        {
             "allCopilots": [
                {
                  "id": 20,
                  "name": "dok_tester",
                  "softwareCopilot": true,
                  "studioCopilot": true
                }
              ]
        }

+ Response 401 (application/json)

        {
            "name":"Unauthorized",
            "value":"401",
            "description":"Authentication credentials were missing or incorrect."
        }

+ Response 403 (application/json)

        {
            "name":"Forbidden",
            "value":"403",
            "description":"The request is understood, but it has been refused or access is not allowed."
        }

+ Response 500 (application/json)

        {
            "name":"Internal Server Error",
            "value":"500",
            "description":"Unknown server error. Please contact support."
        }

+ Response 503 (application/json)

        {
            "name":"Service Unavailable",
            "value":"503",
            "description":"Servers are up but overloaded. Try again later."
        }
        
### Create New Copilot [POST]
+ Attributes
    + username: `dok_tester` (required, string) ... The username
    + isSoftwareCopilot: `true` (required, boolean) ... The isSoftwareCopilot flag
    + isStudioCopilot: `true` (required, boolean) ... The isStudioCopilot flag
    
+ Request (application/json)

    + Headers

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZHwxMzI0NTYiLCJleHAiOjEzOTI4MTc4ODQsImF1ZCI6InRvcGNvZGVyIiwiaWF0IjoxMzkyNzU3ODg0fQ.7X2IKkiyyI1ExSM5GNpdhJ8fGGK5-oAjzccX6YL_BKY

  
   
+ Response 200 (application/json)
        
        {
             "success": true,
             "message": "Copilot dok_tester has been successfully added"
        }
        
+ Response 400 (application/json)

        {
            "name":"Bad Request",
            "value":"400",
            "description":"The request was invalid. An accompanying message will explain why."
        }
        
+ Response 401 (application/json)

        {
            "name":"Unauthorized",
            "value":"401",
            "description":"Authentication credentials were missing or incorrect."
        }

+ Response 403 (application/json)

        {
            "name":"Forbidden",
            "value":"403",
            "description":"The request is understood, but it has been refused or access is not allowed."
        }

+ Response 404 (application/json)

        {
            "name":"Not Found",
            "value":"404",
            "description":"The URI requested is invalid or the requested resource does not exist."
        }

+ Response 409 (application/json)

        {
            "name":"Duplicate Resource",
            "value":"409",
            "description":"The request is understood, but has duplicate resource."
        }
        
+ Response 500 (application/json)

        {
            "name":"Internal Server Error",
            "value":"500",
            "description":"Unknown server error. Please contact support."
        }

+ Response 503 (application/json)

        {
            "name":"Service Unavailable",
            "value":"503",
            "description":"Servers are up but overloaded. Try again later."
        }
        
### Remove Copilot [DELETE]
+ Attributes
    + username: `dok_tester` (required, string) ... The username
    
+ Request (application/json)

    + Headers

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZHwxMzI0NTYiLCJleHAiOjEzOTI4MTc4ODQsImF1ZCI6InRvcGNvZGVyIiwiaWF0IjoxMzkyNzU3ODg0fQ.7X2IKkiyyI1ExSM5GNpdhJ8fGGK5-oAjzccX6YL_BKY

   

+ Response 200 (application/json)
        
        {
             "success": true,
             "message": "Copilot dok_tester has been successfully removed"
        }
        
+ Response 400 (application/json)

        {
            "name":"Bad Request",
            "value":"400",
            "description":"The request was invalid. An accompanying message will explain why."
        }
        
+ Response 401 (application/json)

        {
            "name":"Unauthorized",
            "value":"401",
            "description":"Authentication credentials were missing or incorrect."
        }

+ Response 403 (application/json)

        {
            "name":"Forbidden",
            "value":"403",
            "description":"The request is understood, but it has been refused or access is not allowed."
        }

+ Response 404 (application/json)

        {
            "name":"Not Found",
            "value":"404",
            "description":"The URI requested is invalid or the requested resource does not exist."
        }
        
+ Response 500 (application/json)

        {
            "name":"Internal Server Error",
            "value":"500",
            "description":"Unknown server error. Please contact support."
        }

+ Response 503 (application/json)

        {
            "name":"Service Unavailable",
            "value":"503",
            "description":"Servers are up but overloaded. Try again later."
        }
        
## Reviewers Collection [/admin/reviewers?categoryId={categoryId}]

### List All reviewers [GET]
+ Request (application/json)

    + Headers

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZHwxMzI0NTYiLCJleHAiOjEzOTI4MTc4ODQsImF1ZCI6InRvcGNvZGVyIiwiaWF0IjoxMzkyNzU3ODg0fQ.7X2IKkiyyI1ExSM5GNpdhJ8fGGK5-oAjzccX6YL_BKY



+ Parameters
    + categoryId (required, number, `7`) ... Project Category Id
    
+ Response 200 (application/json)

        {
              "categoryId": 7,
              "reviewers": [
                {
                  "id": 20,
                  "name": "dok_tester",
                  "projectCategoryId": 7,
                  "projectCategoryName": "Architecture",
                  "immune": false
                }
              ]
        }

+ Response 401 (application/json)

        {
            "name":"Unauthorized",
            "value":"401",
            "description":"Authentication credentials were missing or incorrect."
        }

+ Response 403 (application/json)

        {
            "name":"Forbidden",
            "value":"403",
            "description":"The request is understood, but it has been refused or access is not allowed."
        }

+ Response 500 (application/json)

        {
            "name":"Internal Server Error",
            "value":"500",
            "description":"Unknown server error. Please contact support."
        }

+ Response 503 (application/json)

        {
            "name":"Service Unavailable",
            "value":"503",
            "description":"Servers are up but overloaded. Try again later."
        }
        
### Create New Reviewer [POST]
+ Attributes
    + username: `dok_tester` (required, string) ... The username
    + categoryId: `14` (required, number) ... The project category id, you can use category id in query but recommend to use category in body.
    + immune: `true` (optional, boolean) ... The immune_ind flag
    
+ Request (application/json)

    + Headers

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZHwxMzI0NTYiLCJleHAiOjEzOTI4MTc4ODQsImF1ZCI6InRvcGNvZGVyIiwiaWF0IjoxMzkyNzU3ODg0fQ.7X2IKkiyyI1ExSM5GNpdhJ8fGGK5-oAjzccX6YL_BKY

  
   
+ Response 200 (application/json)
        
        {
             "success": true,
             "message": "dok_tester has been successfully added into Assembly Competition Review Board"
        }
        
+ Response 400 (application/json)

        {
            "name":"Bad Request",
            "value":"400",
            "description":"The request was invalid. An accompanying message will explain why."
        }
        
+ Response 401 (application/json)

        {
            "name":"Unauthorized",
            "value":"401",
            "description":"Authentication credentials were missing or incorrect."
        }

+ Response 403 (application/json)

        {
            "name":"Forbidden",
            "value":"403",
            "description":"The request is understood, but it has been refused or access is not allowed."
        }

+ Response 404 (application/json)

        {
            "name":"Not Found",
            "value":"404",
            "description":"The URI requested is invalid or the requested resource does not exist."
        }

+ Response 409 (application/json)

        {
            "name":"Duplicate Resource",
            "value":"409",
            "description":"The request is understood, but has duplicate resource."
        }
        
+ Response 500 (application/json)

        {
            "name":"Internal Server Error",
            "value":"500",
            "description":"Unknown server error. Please contact support."
        }

+ Response 503 (application/json)

        {
            "name":"Service Unavailable",
            "value":"503",
            "description":"Servers are up but overloaded. Try again later."
        }
        
### Remove Reviewer [DELETE]
+ Attributes
    + username: `dok_tester` (required, string) ... The username
    + categoryId: `14` (required, number) ... The project category id, you can use category id in query but recommend to use category in body.
    
+ Request (application/json)

    + Headers

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZHwxMzI0NTYiLCJleHAiOjEzOTI4MTc4ODQsImF1ZCI6InRvcGNvZGVyIiwiaWF0IjoxMzkyNzU3ODg0fQ.7X2IKkiyyI1ExSM5GNpdhJ8fGGK5-oAjzccX6YL_BKY

   

+ Response 200 (application/json)
        
        {
             "success": true,
             "message": "dok_tester has been successfully removed from Assembly Competition Review Board"
        }
        
+ Response 400 (application/json)

        {
            "name":"Bad Request",
            "value":"400",
            "description":"The request was invalid. An accompanying message will explain why."
        }
        
+ Response 401 (application/json)

        {
            "name":"Unauthorized",
            "value":"401",
            "description":"Authentication credentials were missing or incorrect."
        }

+ Response 403 (application/json)

        {
            "name":"Forbidden",
            "value":"403",
            "description":"The request is understood, but it has been refused or access is not allowed."
        }

+ Response 404 (application/json)

        {
            "name":"Not Found",
            "value":"404",
            "description":"The URI requested is invalid or the requested resource does not exist."
        }
        
+ Response 500 (application/json)

        {
            "name":"Internal Server Error",
            "value":"500",
            "description":"Unknown server error. Please contact support."
        }

+ Response 503 (application/json)

        {
            "name":"Service Unavailable",
            "value":"503",
            "description":"Servers are up but overloaded. Try again later."
        }
