database informixoltp;
CREATE SEQUENCE SEQUENCE_USER_GROUP_SEQ
   INCREMENT BY 1 START WITH 300000;
   
CREATE SEQUENCE SEQUENCE_EMAIL_SEQ
   INCREMENT BY 1 START WITH 300000; 
   
CREATE SEQUENCE SEQUENCE_USER_SEQ
   INCREMENT BY 1 START WITH 300000;